apiVersion: v1
kind: Service
metadata:
  name: quote
  annotations:
        a8r.io/description: "Quote of the moment service"
        a8r.io/owner: "No owner"
        a8r.io/chat: "#ambassador"
        a8r.io/bugs: "https://github.com/grangerp/quote/issues"
        a8r.io/documentation: "https://github.com/grangerp/quote/blob/master/README.md"
        a8r.io/repository: "https://github.com/grangerp/quote"
        a8r.io/support: "http://a8r.io/Slack"
        a8r.io/runbook: "https://github.com/datawire/grangerp/blob/master/README.md"
        a8r.io/incidents: "https://github.com/datawire/grangerp/issues"
        a8r.io/rollouts.deployment: quote
        a8r.io/rollouts.image-repo.name: datawire/quote
        a8r.io/rollouts.image-repo.type: dockerhub
        a8r.io/rollouts.mappings: quote-backend
        a8r.io/rollouts.scm.branch: master
        a8r.io/rollouts.scm.path: manifests
        a8r.io/dependencies: "None"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: quote
